source 'https://rubygems.org/'

# App Stack
gem 'sinatra', '~> 1.4'

# Database Stack
gem 'sequel'
gem 'sequel-seed'
gem 'pg'
gem 'puma'
gem 'colorize'
gem 'rack-protection'

# Graphql
gem 'graphql'
gem 'json'

# Token
gem 'rack-jwt'

group :development do
  gem 'rake', '~> 10.0'
  gem 'minitest', '~> 5.2'
  gem 'rack-test', '~> 0.6'
end
