source 'https://rubygems.org/'

# App Stack
gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib'
# Database Stack
gem 'sequel'
gem 'sequel-seed'
gem 'pg'
gem 'colorize'

# Graphql
gem 'graphql'
gem 'graphql-relay'
gem 'json'

group :development do
  gem 'rake', '~> 10.0'
  gem 'minitest', '~> 5.2'
  gem 'rack-test', '~> 0.6'
end
