"""empty message

Revision ID: abb8ee2268df
Revises: None
Create Date: 2016-05-24 18:10:56.962599

"""

# revision identifiers, used by Alembic.
revision = 'abb8ee2268df'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_table('posts',
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('posts_id')
    )
    op.create_table('comments',
    sa.Column('comments_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.posts_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('comments_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('users')
    ### end Alembic commands ###
