source 'https://rubygems.org'

group :development do
  gem 'rake'
end

gem 'puma'
gem 'roda'
gem 'tilt'
gem 'dotenv'

# Graphql
gem 'graphql'

# Database Stack
gem 'sequel'
gem 'sequel-seed'
gem 'pg'
gem 'colorize'

# Protection :)
gem 'rack-protection'

# Token :)
gem 'rack-jwt'
