source 'https://rubygems.org'

group :development do
  gem 'rake'
end

gem 'puma'
gem 'roda'
gem 'tilt'
gem 'dotenv'
gem 'graphql'
gem 'json'
# Database Stack
gem 'sequel'
gem 'sequel-seed'
gem 'pg'
gem 'colorize'
gem 'rack_csrf'
